.PHONY: clean

all: clean
	python3 tuto_vitis_stream.py

build:
	python3 tuto_vitis_stream.py

clean:
	rm -rf prj_tuto_vitis_stream/
	rm KERAS_3layer.json KERAS_3layer_weights.h5  prj_tuto_vitis_stream.tar.gz
